version: '2'

volumes:
  models:

services:
  # ================================= Bot =====================================
  bot:
    image: bot
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    env_file:
      - docker/bot.env
    ports:
      - 5005:5005
      - 5002:5002
    volumes:
      - ./bot:/bot
    command: make run-api
    depends_on:
      - trainer
  trainer:
    build:
      context: .
      dockerfile: ./docker/trainer.Dockerfile
    image: trainer:latest
    command: make train
    volumes:
      - ./bot:/bot
