version: '2'

volumes:
  models:

services:
  # ================================= Bot =====================================
  bot:
    image: bot
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    env_file:
      - docker/bot.env
    ports:
      - 5005:5005
      - 5002:5002
    volumes:
      - ./bot:/bot
    command: make run-api

  trainer:
    ports:
      - 5055:5055
    image: trainer:latest
    command: make train
    volumes:
      - ./bot:/bot

  # =============================== Notebooks =================================
  notebooks:
    build:
      context: .
      dockerfile: ./docker/notebooks.Dockerfile
    volumes:
      - ./bot:/work/bot
      - ./notebooks:/work/notebooks
    ports:
      - 8888:8888

  # =============================== Elastic Stack TODO =================================
  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128
