version: '2'

volumes:
  models:

services:
  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  # ================================= Bot =====================================
  bot:
    image: bot
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    env_file:
      - docker/bot.env
    ports:
      - 5005:5005
      - 5002:5002
    depends_on:
      - actions
      - coach
    volumes:
      - ./bot:/bot
      - ./scripts:/scripts

  coach:
    image: coach:latest
    command: cp -a /src_models/. /models/
    volumes:
      - models:/models/
      - ./coach:/coach
      - ./scripts:/scripts

  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions:/bot/actions
      - ./bot/Makefile:/bot/Makefile
    command: sh -c "make run-actions"


  # =============================== Notebooks =================================
  notebooks:
    build:
      context: .
      dockerfile: ./docker/notebooks.Dockerfile
    volumes:
      - ./bot:/work/bot
      - ./notebooks:/work/notebooks
    ports:
      - 8888:8888
